
MCU          = atmega2560
F_CPU        = 16000000
TARGET       = arduino_mega2560__m2560
LWCLONE_SRC  = ../../main_led.c ../../comm.c ../../led.c ../../panel.c ../../queue.c ../../clock.c ../../mpu6050.c ../../get_millis.c
ADDITIONAL_OBJ = ../../i2cmaster/i2cmaster.o

# LWCLONE_SRC  = ../../main_led2.c

include ../../default.mk
