
MCU          = atmega2560
F_CPU        = 16000000
TARGET       = arduino_mega2560__m2560
LWCLONE_SRC  = ../../main_led.c ../../comm.c ../../led_toys_pwm.c ../../panel.c ../../queue.c ../../clock.c ../../mpu6050.c ../../millis_timer.c ../../twi.c
# ADDITIONAL_OBJ = ../../i2cmaster/twimaster.o

#LWCLONE_SRC  = ../../main_led2.c 

include ../../default.mk


